// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: head_service/head_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TryRegisterPeopleParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryRegisterPeopleParams) Reset() {
	*x = TryRegisterPeopleParams{}
	mi := &file_head_service_head_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryRegisterPeopleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryRegisterPeopleParams) ProtoMessage() {}

func (x *TryRegisterPeopleParams) ProtoReflect() protoreflect.Message {
	mi := &file_head_service_head_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryRegisterPeopleParams.ProtoReflect.Descriptor instead.
func (*TryRegisterPeopleParams) Descriptor() ([]byte, []int) {
	return file_head_service_head_service_proto_rawDescGZIP(), []int{0}
}

func (x *TryRegisterPeopleParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TryRegisterPeopleParams) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

var File_head_service_head_service_proto protoreflect.FileDescriptor

const file_head_service_head_service_proto_rawDesc = "" +
	"\n" +
	"\x1fhead_service/head_service.proto\x12\x0fhead_service.v1\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x17TryRegisterPeopleParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vfamily_name\x18\x02 \x01(\tR\n" +
	"familyName2f\n" +
	"\rPeopleService\x12U\n" +
	"\x11TryRegisterPeople\x12(.head_service.v1.TryRegisterPeopleParams\x1a\x16.google.protobuf.EmptyB?Z=github.com/Konstantin-TT/contract/contract-go/head-service/v1b\x06proto3"

var (
	file_head_service_head_service_proto_rawDescOnce sync.Once
	file_head_service_head_service_proto_rawDescData []byte
)

func file_head_service_head_service_proto_rawDescGZIP() []byte {
	file_head_service_head_service_proto_rawDescOnce.Do(func() {
		file_head_service_head_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_head_service_head_service_proto_rawDesc), len(file_head_service_head_service_proto_rawDesc)))
	})
	return file_head_service_head_service_proto_rawDescData
}

var file_head_service_head_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_head_service_head_service_proto_goTypes = []any{
	(*TryRegisterPeopleParams)(nil), // 0: head_service.v1.TryRegisterPeopleParams
	(*emptypb.Empty)(nil),           // 1: google.protobuf.Empty
}
var file_head_service_head_service_proto_depIdxs = []int32{
	0, // 0: head_service.v1.PeopleService.TryRegisterPeople:input_type -> head_service.v1.TryRegisterPeopleParams
	1, // 1: head_service.v1.PeopleService.TryRegisterPeople:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_head_service_head_service_proto_init() }
func file_head_service_head_service_proto_init() {
	if File_head_service_head_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_head_service_head_service_proto_rawDesc), len(file_head_service_head_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_head_service_head_service_proto_goTypes,
		DependencyIndexes: file_head_service_head_service_proto_depIdxs,
		MessageInfos:      file_head_service_head_service_proto_msgTypes,
	}.Build()
	File_head_service_head_service_proto = out.File
	file_head_service_head_service_proto_goTypes = nil
	file_head_service_head_service_proto_depIdxs = nil
}
